  - name: rhel8STIG
    src: https://github.com/ansible-lockdown/RHEL8-STIG
  - name: amazon2023CIS
    src: https://github.com/ansible-lockdown/AMAZON2023-CIS
  - name: ubuntu22CIS
    src: https://github.com/ansible-lockdown/UBUNTU22-CIS