---
- hosts: all
  become: true
  
  tasks:
    - name: Find result files
      find:
        paths: /opt/
        recurse: yes
        file_type: file
        patterns: "*.json"
      register: found_files
    - name: Get latest file
      set_fact:
        latest_file: "{{ found_files.files | sort(attribute='mtime', reverse=True) | first }}"
    - name: Slurp file contents
      slurp:
        src: "{{ latest_file.path }}"
      register: slurped_file
    - name: Set artifact
      set_stats:
        data:
          latest_results: "{{ slurped_file.content | b64decode }}"

