---
- hosts: all
  become: true
  gather_facts: yes
  
  tasks:
    - name: Audit Ubuntu 22
      include_role:
        name: ubuntu22CIS
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "22"
      vars:
        ubtu22cis_rule_5_3_4: false
        ubtu22cis_rule_1_4_3: false
        audit_only: true
        run_audit: true
        setup_audit: true
    - name: Find result files
      find:
        paths: /opt
        recurse: yes
        file_type: file
      register: found_files
    - name: Slurp file contents
      slurp:
        src: "{{ item.path }}"
      loop: "{{ found_files.files }}"
      register: slurped_files
    - name: Set facts
      set_fact:
        "file_{{ item.item.path | basename }}": "{{ item.content | b64decode }}"
      loop: "{{ slurped_files.results }}"
    - name: Unsupported OS
      debug:
        msg: "This OS or OS version is not supported"
      when: >
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")
