---
- hosts: all
  become: true
  
  tasks:
    - name: Audit Ubuntu 22
      include_role:
        name: ubuntu22CIS
      when:
        - ansible_facts['ansible_distribution'] == "Ubuntu"
        - ansible_facts['ansible_distribution_major_version'] == "22"
      vars:
        ubtu22cis_rule_5_3_4: false
        ubtu22cis_rule_1_4_3: false
        audit_only: true
        run_audit: true
        setup_audit: true
